#!/usr/bin/env bash
#MISE description="Profile benchmarks (prefer bench:cpu or bench:mem for options)"
#USAGE arg "<mode>" help="Profile kind" {
#USAGE   choices "cpu" "mem"
#USAGE }
set -euo pipefail
exec mise run "bench:${usage_mode?}"
