package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"
)

var (
	errCobraFishTemplateChanged   = errors.New("pinned Cobra Fish completion template changed")
	errUnsupportedCompletionShell = errors.New("unsupported completion shell")
)

const (
	completionCommandName = "completion"
	fishShellName         = "fish"
	cobraFishCurrentToken = "set -l lastArg (string escape -- (commandline -ct))"
	cobraFishPrefixFilter = "set -l prefix (commandline -t | string escape --style=regex)"
)

func configureCompletionGeneration(root *cobra.Command) {
	root.InitDefaultCompletionCmd()
	completion, _, err := root.Find([]string{completionCommandName})
	if err != nil || completion.Name() != completionCommandName {
		panic("locate Cobra completion command")
	}
	for _, shell := range completion.Commands() {
		shell.RunE = runCompletionGeneration
	}
}

func runCompletionGeneration(cmd *cobra.Command, _ []string) error {
	noDescriptions := cmd.Root().CompletionOptions.DisableDescriptions
	if cmd.Flags().Lookup("no-descriptions") != nil {
		var err error
		noDescriptions, err = cmd.Flags().GetBool("no-descriptions")
		if err != nil {
			return fmt.Errorf("read %s completion description option: %w", cmd.Name(), err)
		}
	}
	root, output := cmd.Root(), cmd.OutOrStdout()
	var err error
	switch cmd.Name() {
	case "bash":
		err = root.GenBashCompletionV2(output, !noDescriptions)
	case "zsh":
		if noDescriptions {
			err = root.GenZshCompletionNoDesc(output)
		} else {
			err = root.GenZshCompletion(output)
		}
	case "powershell":
		if noDescriptions {
			err = root.GenPowerShellCompletion(output)
		} else {
			err = root.GenPowerShellCompletionWithDesc(output)
		}
	case fishShellName:
		return generateFishCompletion(cmd, !noDescriptions)
	default:
		return fmt.Errorf("%w %q", errUnsupportedCompletionShell, cmd.Name())
	}
	if err != nil {
		return fmt.Errorf("generate %s completion: %w", cmd.Name(), err)
	}
	return nil
}

func generateFishCompletion(cmd *cobra.Command, descriptions bool) error {
	var generated bytes.Buffer
	if err := cmd.Root().GenFishCompletion(&generated, descriptions); err != nil {
		return fmt.Errorf("generate Fish completion: %w", err)
	}
	script, err := normalizeCobraFishTokens(generated.String())
	if err != nil {
		return err
	}
	if _, err := io.WriteString(cmd.OutOrStdout(), script); err != nil {
		return fmt.Errorf("write Fish completion: %w", err)
	}
	return nil
}

func normalizeCobraFishTokens(script string) (string, error) {
	replacements := []struct {
		old string
		new string
	}{
		{cobraFishCurrentToken, "set -l lastArg (commandline -ct | string unescape | string escape --)"},
		{cobraFishPrefixFilter, "set -l prefix (commandline -t | string unescape | string escape --style=regex)"},
	}
	for _, replacement := range replacements {
		if strings.Count(script, replacement.old) != 1 {
			return "", fmt.Errorf("adapt generated Fish completion: %w near %q", errCobraFishTemplateChanged, replacement.old)
		}
		script = strings.Replace(script, replacement.old, replacement.new, 1)
	}
	return script, nil
}
