package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"
)

var errCobraFishTemplateChanged = errors.New("pinned Cobra Fish completion template changed")

const (
	cobraFishCurrentToken = "set -l lastArg (string escape -- (commandline -ct))"
	cobraFishPrefixFilter = "set -l prefix (commandline -t | string escape --style=regex)"
)

func configureFishCompletionGeneration(root *cobra.Command) {
	root.InitDefaultCompletionCmd()
	fish, _, err := root.Find([]string{"completion", "fish"})
	if err != nil || fish.Name() != "fish" {
		panic("locate Cobra Fish completion command")
	}
	fish.RunE = func(cmd *cobra.Command, _ []string) error {
		noDescriptions, err := cmd.Flags().GetBool("no-descriptions")
		if err != nil {
			return fmt.Errorf("read Fish completion description option: %w", err)
		}
		var generated bytes.Buffer
		if err := cmd.Root().GenFishCompletion(&generated, !noDescriptions); err != nil {
			return fmt.Errorf("generate Fish completion: %w", err)
		}
		script, err := normalizeCobraFishTokens(generated.String())
		if err != nil {
			return err
		}
		if _, err := io.WriteString(cmd.OutOrStdout(), script); err != nil {
			return fmt.Errorf("write Fish completion: %w", err)
		}
		return nil
	}
}

func normalizeCobraFishTokens(script string) (string, error) {
	replacements := []struct {
		old string
		new string
	}{
		{cobraFishCurrentToken, "set -l lastArg (commandline -ct | string unescape | string escape --)"},
		{cobraFishPrefixFilter, "set -l prefix (commandline -t | string unescape | string escape --style=regex)"},
	}
	for _, replacement := range replacements {
		if strings.Count(script, replacement.old) != 1 {
			return "", fmt.Errorf("adapt generated Fish completion: %w near %q", errCobraFishTemplateChanged, replacement.old)
		}
		script = strings.Replace(script, replacement.old, replacement.new, 1)
	}
	return script, nil
}
