package cmd

import (
	"errors"
	"net/http"
	"strconv"
	"strings"
	"testing"
	"unicode/utf8"
)

const maxFuzzHTTPHeadInputSize = 1 << 12

// FuzzWriteHTTPHead states the rendering contract independently of the escaper
// that enforces it: whatever a peer puts in a header name or value, the head
// occupies exactly one line per emitted value plus a status line and a blank
// separator, stays valid UTF-8, and carries no raw control characters. A value
// or name that smuggled a newline through would add a line and fail the count,
// which is the injection property the escaping exists to provide.
//
// http.Header is an ordinary map, so nothing prevents control bytes in names,
// and Go randomizes the iteration order. Every assertion here is therefore
// order-invariant: counts, set membership, and the status line that is always
// written first.
func FuzzWriteHTTPHead(f *testing.F) {
	f.Add("HTTP/1.1", "200 OK", "Content-Type\x01text/plain", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "X-Multi\x01one\x01two\x00X-Other\x01value", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "X-Test\x01value\nInjected: smuggled", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "Smuggled\nName\x01value", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "X-CR\x01value\r\nInjected: smuggled", false, uint8(0))
	f.Add("HTTP/1.1\r\nInjected: smuggled", "200 OK", "", false, uint8(0))
	f.Add("HTTP/1.1", "200 \x00OK\x1b[2J", "", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "X-Binary\x01\xff\xfe\x00X-Name\xff\x01value", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "X-Empty\x01", false, uint8(0))
	f.Add("HTTP/1.1", "200 OK", "X-No-Values", false, uint8(0))
	f.Add("", "", "", false, uint8(0))
	for failureCall := range uint8(5) {
		f.Add("HTTP/1.1", "200 OK", "X-One\x01a\x00X-Two\x01b", true, failureCall)
	}

	f.Fuzz(func(t *testing.T, proto, status, headerBlob string, outputFail bool, outputFailureCall uint8) {
		if len(proto)+len(status)+len(headerBlob) > maxFuzzHTTPHeadInputSize {
			t.Skip()
		}
		header, values := fuzzHTTPHeader(headerBlob)
		response := &http.Response{Proto: proto, Status: status, Header: header}

		baseline := &fuzzHTTPRecordingWriter{}
		if err := writeHTTPHead(baseline, response); err != nil {
			t.Fatalf("write HTTP head: %v", err)
		}
		if outputFail {
			output := &fuzzHTTPFailOnceWriter{failAt: int(outputFailureCall) % baseline.calls}
			if err := writeHTTPHead(output, response); !errors.Is(err, errFuzzHTTPOutput) {
				t.Fatalf("head error = %v, want output failure on call %d of %d", err, output.failAt, baseline.calls)
			}
			return
		}

		head := string(baseline.output)
		if !utf8.ValidString(head) {
			t.Fatalf("HTTP head is not valid UTF-8: %x", head)
		}
		for _, char := range head {
			if char != '\n' && !strconv.IsPrint(char) {
				t.Fatalf("HTTP head contains non-printing rune %U: %q", char, head)
			}
		}
		if !strings.HasSuffix(head, "\n\n") {
			t.Fatalf("HTTP head %q does not end with a blank separator line", head)
		}
		lines := strings.Split(strings.TrimSuffix(head, "\n\n"), "\n")
		if len(lines) != 1+values {
			t.Fatalf("HTTP head rendered %d lines, want 1 status line and %d header lines: %q", len(lines), values, head)
		}
		checkFuzzHTTPHeadContent(t, lines, proto, status, header)
	})
}

// checkFuzzHTTPHeadContent pins content wherever escaping is required to be the
// identity. A name or value made entirely of printable runes must survive
// verbatim, so its line is predictable without reimplementing the escaper.
func checkFuzzHTTPHeadContent(t *testing.T, lines []string, proto, status string, header http.Header) {
	t.Helper()
	if isVerbatimDiagnosticValue(proto) && isVerbatimDiagnosticValue(status) && lines[0] != proto+" "+status {
		t.Fatalf("status line = %q, want %q", lines[0], proto+" "+status)
	}

	remaining := make(map[string]int, len(lines)-1)
	for _, line := range lines[1:] {
		if line == "" {
			t.Fatalf("HTTP head emitted an empty header line: %q", lines)
		}
		remaining[line]++
	}
	verbatim := true
	for name, headerValues := range header {
		for _, value := range headerValues {
			if !isVerbatimDiagnosticValue(name) || !isVerbatimDiagnosticValue(value) {
				verbatim = false
				continue
			}
			line := name + ": " + value
			if remaining[line] == 0 {
				t.Fatalf("printable header %q did not render as %q; lines %q", name, line, lines[1:])
			}
			remaining[line]--
		}
	}
	if !verbatim {
		return
	}
	for line, count := range remaining {
		if count != 0 {
			t.Fatalf("HTTP head rendered %d unaccounted copies of %q", count, line)
		}
	}
}

// fuzzHTTPHeader builds a header map from generated bytes. Entries are
// separated by NUL and split from their values by SOH, so generated names carry
// arbitrary bytes rather than only what http.Header.Set would canonicalize.
func fuzzHTTPHeader(blob string) (http.Header, int) {
	header := make(http.Header)
	values := 0
	if blob == "" {
		return header, 0
	}
	for _, entry := range strings.Split(blob, "\x00") {
		fields := strings.Split(entry, "\x01")
		if len(fields) == 1 {
			continue
		}
		header[fields[0]] = append(header[fields[0]], fields[1:]...)
		values += len(fields) - 1
	}
	return header, values
}

// isVerbatimDiagnosticValue reports whether diagnostic escaping must leave the
// value untouched: every rune printable, and no invalid UTF-8 to be replaced.
func isVerbatimDiagnosticValue(value string) bool {
	if !utf8.ValidString(value) {
		return false
	}
	for _, char := range value {
		if !strconv.IsPrint(char) {
			return false
		}
	}
	return true
}
