name: Renovate config dry run

on:
  pull_request:
    paths:
      - renovate.json
      - mise.toml
      - .github/workflows/renovate.yml
      - .github/workflows/renovate-config-dry-run.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: sosheskaz-systems/reno/.github/workflows/renovate-config-dry-run.yml@03e576688a2184b4928f78f58084e060dba22c75 # v1.3.0
    with:
      install-go: true
      log-level: ${{ vars.RENOVATE_LOG_LEVEL || 'info' }}
    secrets:
      RENOVATE_APP_PRIVATE_KEY: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
